shufflePlaylist:  main.c
	gcc -o shufflePlaylist main.c
	./shufflePlaylist
clean:  
	rm -f ./shufflePlaylist ./shuffleMonday.txt ./shuffleTuesday.txt ./shuffleWednesday.txt ./shuffleThursday.txt ./shuffleFriday.txt ./shuffleSaturday.txt ./shuffleSunday.txt
